/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JDialog;
import javax.swing.JRootPane;
import kontroler.Kontroler;

/**
 *
 * @author acer e1
 */
public class FormGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FormGlavna
     */
    public FormGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmOsoba = new javax.swing.JMenu();
        jmiOsobaPrikaziCombo = new javax.swing.JMenuItem();
        jmiOsobaPrikaziTabela = new javax.swing.JMenuItem();
        jmiOsobaUnos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavna forma");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/wolf.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jmOsoba.setText("Osoba");

        jmiOsobaPrikaziCombo.setText("Prikazi combo");
        jmiOsobaPrikaziCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOsobaPrikaziComboActionPerformed(evt);
            }
        });
        jmOsoba.add(jmiOsobaPrikaziCombo);

        jmiOsobaPrikaziTabela.setText("Prikazi tabela");
        jmiOsobaPrikaziTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOsobaPrikaziTabelaActionPerformed(evt);
            }
        });
        jmOsoba.add(jmiOsobaPrikaziTabela);

        jmiOsobaUnos.setText("Unos");
        jmiOsobaUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOsobaUnosActionPerformed(evt);
            }
        });
        jmOsoba.add(jmiOsobaUnos);

        jMenuBar1.add(jmOsoba);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiOsobaPrikaziComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOsobaPrikaziComboActionPerformed
        JDialog formaPrikaz = new FormOsobaPrikazCombo(this, false);
        formaPrikaz.setVisible(true);
        Kontroler.getInstance().registrujFormu(formaPrikaz);
    }//GEN-LAST:event_jmiOsobaPrikaziComboActionPerformed

    private void jmiOsobaUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOsobaUnosActionPerformed
        JDialog formaUnos = new FormOsobaUnos(this, false);
        formaUnos.setVisible(true);
    }//GEN-LAST:event_jmiOsobaUnosActionPerformed

    private void jmiOsobaPrikaziTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOsobaPrikaziTabelaActionPerformed
        JDialog formaPrikazTabela = new FormOsobaPrikazTabela(this, false);
        formaPrikazTabela.setVisible(true);
        Kontroler.getInstance().registrujFormu(formaPrikazTabela);
    }//GEN-LAST:event_jmiOsobaPrikaziTabelaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmOsoba;
    private javax.swing.JMenuItem jmiOsobaPrikaziCombo;
    private javax.swing.JMenuItem jmiOsobaPrikaziTabela;
    private javax.swing.JMenuItem jmiOsobaUnos;
    // End of variables declaration//GEN-END:variables
    
}
